spring:
  application:
    name: noma-orchestrator
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
    consumer:
      group-id: system-info-group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
  cache:
    type: caffeine
    expireAfterWrite: 24
    maximumSize: 98
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: qwerty
    url: jdbc:postgresql://localhost:5432/dev_noma_orchestrator
  liquibase:
    database-change-log-lock-table: ${spring.application.name}_DATABASECHANGELOCK
    change-log: db.changelog/changelog-master.yaml
server:
  port: 8888
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  info:
    title: My API
    version: 1.0.0
    description: API Documentation
integration:
  retry:
    config:
      maxAttempts: 3                      # Максимальное число попыток (первая + 2 повтора)
      initialInterval: 2000               # Начальная задержка между попытками (2 сек)
      multiplier: 2.0                     # Во сколько раз увеличивать задержку
      maxInterval: 10000                  # Максимальная задержка между попытками (10 сек)
      retryableExceptions: # Какие исключения считаются «временными» и должны ретраиться
        - java.net.SocketTimeoutException
        - org.springframework.web.client.ResourceAccessException
        - java.io.IOException
      connectTimeout: 2000 # максимальное время (мс) ожидания установки соединения с внешним сервисом
      readTimeout: 5000 # максимальное время (мс) ожидания получения ответа от внешнего сервиса после установления соединения
  complex-check:
    complex-check-url: ${COMPLEX_CHECK_URL:http://localhost:8081/check}
  fraud:
    fraud-url: ${FRAUD_URL:http://localhost:8082/fraud/check}
logging:
  level:
    root: INFO



