services:
  db:
    image: postgres:latest
    container_name: noma_db
    environment:
      POSTGRES_DB: dev_noma_orchestrator
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - noma_postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring

  db-info-system:
    image: postgres:latest
    container_name: info_system_db
    environment:
      POSTGRES_DB: info_system_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - info_postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring

  db-risk:
    image: postgres:latest
    container_name: risk_db
    environment:
      POSTGRES_DB: risk_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5434:5432"
    volumes:
      - risk_postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring


  redis:
    image: redis:7-alpine
    container_name: redis-noma
    command: redis-server --requirepass 123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    environment:
      - RI_PROXY_ENABLE=true
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - monitoring

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - monitoring

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_DOCKER://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_DOCKER://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Важно для доступа к хосту

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Для тестирования данных из Grafana

volumes:
  noma_postgres_data:
  info_postgres_data:
  risk_postgres_data:
  redis_data:
  redis_insight_data:
  prometheus_data:
  grafana_data:


networks:
  monitoring:
    driver: bridge