version: '3'

services:
  grafana:
    container_name: grafana_noma
    image: bitnami/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data/:/opt/bitnami/grafana/data/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    container_name: prometheus_noma
    image: bitnami/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dev_noma_orchestrator
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: